Review screen with Customer's Name, Experience and Rating Slider
shokeenashish4/figma_shopping_app pull request #3
Opened 2023-12-02 15:32 UTC by shokeenashish4

2023-12-03 06:03 UTC, shubhamsinghshubham777 commented
@shokeenashish4 Can you add some screenshots or screen recordings in the description of this PR for the screens you have created?

2023-12-03 06:04 UTC, shubhamsinghshubham777 commented
Also, you can assign this ticket to yourself (i.e. add your name in the `Assignees` section)

2023-12-03 06:17 UTC, shubhamsinghshubham777 requested changes

2023-12-03 06:17 UTC, shubhamsinghshubham777 commented on lib/screens/cart_screen.dart
> +        clipBehavior: Clip.none,
Did we verify whether we really needed this line of code? If not, could you please do the same?

2023-12-03 06:17 UTC, shubhamsinghshubham777 commented on lib/screens/cart_screen.dart
> +                                fontFamily: "Inter",
Learn about [DefaultTextStyle](https://api.flutter.dev/flutter/widgets/DefaultTextStyle-class.html) widget to avoid having to write `fontFamily: "Inter"` (or any repetitive code related to TextStyle) over and over again.

In short, instead of writing:
```dart
Column(
  children: [
    Text("text 1", style: TextStyle(fontFamily: "Inter")),
    Text("text 2", style: TextStyle(fontFamily: "Inter")),
    Text("text 3", style: TextStyle(fontFamily: "Inter")),
  ]
)
```

you can write:
```dart
DefaultTextStyle(
  style: TextStyle(fontFamily: "Inter"),
  child: Column(
    children: [
      Text("text 1"),
      Text("text 2"),
      Text("text 3"),
    ]
  )
)
```

2023-12-03 06:17 UTC, shubhamsinghshubham777 commented on lib/screens/onboarding/forgot_pwd_screen.dart
> +      lowerTextAction: "",
Instead of having to pass a blank string, update `OnboardingScreenScaffold` in a way that it defaults to a value of `null` and gives the same output as passing a blank string so that you don't have to write this line of code `lowerTextAction: ""` at all.

2023-12-03 06:17 UTC, shubhamsinghshubham777 commented on lib/screens/onboarding/verification_code_screen.dart
> +                    child: Padding(
Extract it all into a single widget, because we're just repeating the same code multiple times here. It should instead look like this:

```dart
MyTextField(),
MyTextField(),
MyTextField(),
MyTextField(),
```

Of course, please try to name it better than `MyTextField` 😂

2023-12-07 06:01 UTC, shokeenashish4 commented on lib/screens/cart_screen.dart
> +                                fontFamily: "Inter",
Repetitive code removed and Widgets are now wrapped with DefaultTextStyle widget.

2023-12-07 06:17 UTC, shokeenashish4 commented on lib/screens/cart_screen.dart
> +        clipBehavior: Clip.none,
The clipBehavior property has been removed.

2023-12-07 07:06 UTC, shubhamsinghshubham777 approved these changes
LGTM 👍🏻 🚀

2023-12-07 07:12 UTC, merged