Implement Fake Data Layer
shokeenashish4/figma_shopping_app pull request #8
Opened 2023-12-18 10:43 UTC by shokeenashish4

This PR implements a fake data layer that allows a user to verify the App's behavior without having to utilize real data sources.

2023-12-23 12:38 UTC, shubhamsinghshubham777 requested changes
Please check out the comments @shokeenashish4 and please also add demo videos/screenshots in this PR's description ✅

2023-12-23 12:38 UTC, shubhamsinghshubham777 commented on lib/data/products_repository.dart
There's no code in this file yet. We can remove it.

2023-12-23 12:38 UTC, shubhamsinghshubham777 commented on lib/ui/screens/dashboard_screen.dart
> +  static const List<Widget> _widgetOptions = <Widget>[
Do we really need to make this variable `static`?

2023-12-23 12:38 UTC, shubhamsinghshubham777 commented on lib/ui/screens/onboarding/signup_onboarding_screen.dart
> +                );
No need to use `Future.delayed` here. Use Future.delayed in `authRepo.signUp`'s implementation 👍🏻

2023-12-23 12:38 UTC, shubhamsinghshubham777 commented on lib/ui/screens/onboarding/social_onboarding_screen.dart
> +          },
While waiting for the response, we can show some kind of indication on the screen [maybe a circular progress indicator or `Loading...` text] (and this applies to all screens throughout the app) such that the user is never left hanging and he always gets some kind of response from the app.

2023-12-23 12:38 UTC, shubhamsinghshubham777 commented on lib/ui/screens/onboarding/social_onboarding_screen.dart
> +            );
We're using this exact same code snippet in both buttons. Better to extract it out as a function instead 👍🏻

2023-12-23 12:38 UTC, shubhamsinghshubham777 commented on lib/ui/screens/onboarding/social_onboarding_screen.dart
> +        },
We can rewrite this to `onPressed: onTap`

2023-12-23 12:38 UTC, shubhamsinghshubham777 commented on lib/ui/screens/onboarding/verification_code_screen.dart
> +          },
Optional: We can shorten this down to `onChanged: (_) => onSubmitted()`

2023-12-23 12:38 UTC, shubhamsinghshubham777 commented on pubspec.yaml
> +  easy_sidemenu: ^0.5.0
Are we using any of these dependencies in the code till now? If not, we can remove it 👍🏻

2023-12-23 13:30 UTC, shokeenashish4 commented on lib/data/products_repository.dart
done

2023-12-26 10:50 UTC, shokeenashish4 commented on lib/ui/screens/onboarding/social_onboarding_screen.dart
> +            );
done.

2023-12-26 10:50 UTC, shokeenashish4 commented on lib/ui/screens/onboarding/social_onboarding_screen.dart
> +        },
done.

2023-12-26 10:50 UTC, shokeenashish4 commented on lib/ui/screens/onboarding/verification_code_screen.dart
> +          },
done

2023-12-26 10:50 UTC, shokeenashish4 commented on pubspec.yaml
> +  easy_sidemenu: ^0.5.0
removed

2023-12-26 12:00 UTC, shokeenashish4 commented on lib/ui/screens/onboarding/social_onboarding_screen.dart
> +          },
done

2023-12-26 12:08 UTC, shokeenashish4 commented on lib/ui/screens/onboarding/signup_onboarding_screen.dart
> +                );
done

2023-12-26 12:10 UTC, shokeenashish4 commented on lib/ui/screens/dashboard_screen.dart
> +  static const List<Widget> _widgetOptions = <Widget>[
Removed the static and made it a 'final' list instead.

2023-12-26 14:57 UTC, shubhamsinghshubham777 requested changes

2023-12-26 14:57 UTC, shubhamsinghshubham777 commented on lib/ui/screens/onboarding/login_screen.dart
> +                    );
Let's remove this as this LOC (Line of code) has no effect.

2023-12-26 14:57 UTC, shubhamsinghshubham777 commented on lib/ui/screens/onboarding/new_pwd_screen.dart
> +                  const Center(child: CircularProgressIndicator());
Same. Let's remove this as well.

2023-12-28 06:55 UTC, shokeenashish4 commented
Fixed the code with the changes you recommended

2023-12-28 10:52 UTC, shubhamsinghshubham777 approved these changes

2023-12-28 11:16 UTC, merged